### ISSUE TITLE
Cannot find name 'zone'

### ISSUE THREAD

**Issue by drozzy** [ShMcK/ng2-socially-tutorial#6]
I get this error in Step 3, after implementing this code:

```
import {Component, View, NgFor, bootstrap} from 'angular2/angular2';

import {Parties} from 'collections/parties';

@Component({
  selector: 'app'
})
@View({
  templateUrl: "client/index.ng.html",
  directives: [NgFor]
})
class Socially {
  constructor () {
    Tracker.autorun(zone.bind(() => {
      this.parties = Parties.find().fetch();
    }));
  }
}

bootstrap(Socially);
```

**Comment by ShMcK** [comment]
Sorry, this tutorial has been deprecated. 

There is a new version I would recommend following at [angular-meteor.com](http://angular-meteor.com/tutorials/angular2/3-way-data-binding) with the parties tutorial repo [here](https://github.com/Urigo/Meteor-Angular2/tree/master/examples/parties).
